environment: 'dev'

dev:
    name: 'Pokedex'
    description: 'Just a simple inventory manager'
    url: 'http://localhost:8080/'
    database:
        username: 'root'
        password: ''
        name: 'inventory'
        host: 'localhost'
        type: 'mysql'
        port: 3306
    debug: true
    twig:
        cache: false
    salt: 'd@3MqemJGlE!0v5g'
    mail:
        from: 'tdt4237mailer@gmail.com'
        host: 'smtp.gmail.com'
        username: 'tdt4237mailer@gmail.com'
        password: 'YF96YtnqvoPt'
        port: '587'

prod:
    name: 'Pokedex'
    description: 'Just a simple inventory manager'
    url: 'http://localhost:8080/'
    database:
        username: 'root'
        password: ''
        name: 'inventory'
        host: 'localhost'
        type: 'mysql'
        port: 3306
    debug: false
    twig:
        cache: false
    salt: 'test'
    mail:
        from: 'root@root.com'
        host: 'localhost'
        username: null
        password: null
        port: 1025
